# Generated by Django 3.0.3 on 2020-09-11 19:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=200)),
                ('document_author', models.CharField(max_length=30)),
                ('Creation_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('Section_id', models.AutoField(primary_key=True, serialize=False)),
                ('Section_Heading', models.CharField(max_length=200)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('Subsection_id', models.AutoField(primary_key=True, serialize=False)),
                ('Subsection_heading', models.CharField(max_length=200)),
                ('Subsection_sequence', models.CharField(default='', max_length=20)),
                ('Section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Section')),
            ],
        ),
        migrations.CreateModel(
            name='Para',
            fields=[
                ('Para_id', models.AutoField(primary_key=True, serialize=False)),
                ('Para_heading', models.CharField(max_length=200)),
                ('Para_content', models.TextField()),
                ('Subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Subsection')),
            ],
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('Img_id', models.AutoField(primary_key=True, serialize=False)),
                ('Img_heading', models.CharField(max_length=100)),
                ('Img_Data', models.ImageField(blank=True, null=True, upload_to=main.models.upload_to)),
                ('Img_url', models.URLField(default='https://www.google.com/')),
                ('Subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Subsection')),
            ],
        ),
    ]
