# Generated by Django 3.0.3 on 2020-09-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_para_para_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='img',
            name='overall_number',
        ),
        migrations.RemoveField(
            model_name='para',
            name='overall_number',
        ),
        migrations.RemoveField(
            model_name='subsection',
            name='Subsection_item_count',
        ),
        migrations.RemoveField(
            model_name='subsection',
            name='Subsection_sequence',
        ),
        migrations.AlterField(
            model_name='para',
            name='para_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
