# Generated by Django 3.0.3 on 2020-09-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200913_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='img_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subsection',
            name='Subsection_sequence',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='para',
            name='para_number',
            field=models.IntegerField(default=0),
        ),
    ]
