# Generated by Django 3.0.3 on 2020-09-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200915_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='Img_Data',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/'),
        ),
    ]
